# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyLatestCreation' do
  pod 'AppCenter/Crashes', '~> 1.11.0'
  pod 'AppCenter/Analytics', '~> 1.11.0'
  pod 'AppCenterReactNativeShared', '~> 1.10.0'
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyLatestCreation

  

  platform :ios, '9.0'
  target 'MyLatestCreationTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'MyLatestCreation-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MyLatestCreation-tvOS

  target 'MyLatestCreation-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
